Carousel leaderboard
arkavidia-hmif/itfest-frontend pull request #1
Opened 2020-11-20 07:01 UTC by akromiafif

2020-12-03 09:52 UTC, jrandiny requested changes

2020-12-03 09:52 UTC, jrandiny commented on components/Carousel.tsx
> +interface CarouselProps {
Migrasi ke carousel yang dipake yang lain aja, supaya bs mobile swipe

2020-12-03 09:52 UTC, jrandiny commented on components/LeaderBoard.tsx
> +          font-weight: bold;
Kenapa gak pake `<b>` aja di paragrafnya, cuman satu ini

2020-12-03 09:52 UTC, jrandiny commented on components/LeaderBoard.tsx
> +          width: 50%;
Hmmm, mending pake sistem bootstrap breakpoint

2020-12-03 09:52 UTC, jrandiny commented on components/LeaderBoardChild.tsx
> +          float: left;
Mending pake bootstrap juga untuk layouting

2020-12-03 09:52 UTC, jrandiny commented on styles/theme.ts
> +    pipi: "linear-gradient(120deg, rgba(254, 148, 171, 1) 0%, rgba(144, 106, 247, 1) 100%)"
pipi?, pink-pink?

2020-12-05 13:45 UTC, akromiafif commented on components/Carousel.tsx
> +interface CarouselProps {
kak ini maksutnya gimana ya

2020-12-30 14:54 UTC, jrandiny requested changes
- Ukuran font masih jelek saat responsive

2020-12-30 14:54 UTC, jrandiny commented on components/Carousel.tsx
> +          @media (max-width: 575.98px) {
Pake bootstrap punya breakpoint angka https://getbootstrap.com/docs/4.0/layout/grid/#grid-options kecuali terpaksa

2021-01-16 16:38 UTC, jrandiny commented
Ini gimana kabarnya?

2021-01-24 13:57 UTC, jrandiny approved these changes

2021-01-24 13:57 UTC, merged