Merch store
arkavidia-hmif/itfest-frontend pull request #2
Opened 2020-11-30 12:56 UTC by nthnieljson

2020-12-03 09:47 UTC, jrandiny requested changes

2020-12-03 09:47 UTC, jrandiny commented on components/merchstore/MerchStoreContainer.tsx
> +  const customArrow = ({
Mungkin bisa dipisah component, karena panjang

2020-12-03 09:47 UTC, jrandiny commented on components/merchstore/MerchStoreContainer.tsx
> +  const MerchStoreItems = [
Ditaro di file constant terpisah aja sementara

2020-12-03 09:47 UTC, jrandiny commented on components/merchstore/MerchStoreContainer.tsx
> +            display: flex;
Misal banyak yang butuh display:flex, bisa dibuat kelas generik untuk itu, tapi btw bootstrap juga udah punya kayak `d-flex` yang bisa dipake

2020-12-03 09:47 UTC, jrandiny commented on components/merchstore/MerchStoreContainer.tsx
> +          @media only screen and (max-width: 400px) {
Breakpoint dimasukin ke file konstanta terpisah aja, dan kalau bisa dimiripin sama punya bootstrap

2020-12-03 09:47 UTC, jrandiny commented on package.json
> +    "styled-components": "^5.2.1",
Ini perlu ya?

2020-12-03 10:44 UTC, nthnieljson commented on package.json
> +    "styled-components": "^5.2.1",
itu salah satu dependency nya "react-elastic-carousel" kak

2020-12-30 14:45 UTC, jrandiny commented
Tolong ukurannya diperhatikan lagi, masih terlalu besar

2021-01-12 07:31 UTC, merged