Company profile
arkavidia-hmif/itfest-frontend pull request #4
Opened 2020-11-30 13:27 UTC by 16519111

Untuk sementara aku pake index.tsx buat routing ke main sama alternatifnya.

Untuk Alternatif :
import CompanyProfile from "./company-profile/companyprofilealt";

Untuk Main : 
import CompanyProfile from "./company-profile/companyprofilemain";

Kemarin juga sempet install library react-elastic-carousel yang udh dicocokin versinya sama niel

2020-12-03 09:43 UTC, jrandiny requested changes
Overall notes, stylingnya banyak redundan

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/Challenge/challenge.tsx
> +      {(done) ?
Ini ifnya dibawa keluar aja supaya lebih rapi
```
if(something){
return()
}else{
return()
}
```

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/Gallery/gallery-alt.tsx
> +                  {pages.map(() => {
Langsung return mapnya aja, gak butuh fragment lagi

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/Gallery/gallery-alt.tsx
> +        .flex-container {
why not bootstrap

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/Gallery/gallery-main.tsx
> +                  {pages.map(() => {
Terlihat bisa digabung componentnya

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/Video/video.tsx
> +            .flex-container {
Bootstrap

2020-12-03 09:43 UTC, jrandiny commented on components/commons/company-profile/about-us.tsx
> +
kosong

2020-12-03 09:43 UTC, jrandiny commented on package.json
> +    "styled-components": "^5.2.1",
hmmm kenapa ini? bukankah dah ada styled jsx

2020-12-03 09:43 UTC, jrandiny commented on pages/company-profile/companyprofilealt.tsx
> +        .grid-container {
dimanakah grid-container ini

2020-12-03 09:43 UTC, jrandiny commented on pages/company-profile/companyprofilemain.tsx
> +        .grid-container {
Ini juga, kenapa ada ini tapi gada komponen dengan kelas itu

2020-12-03 09:43 UTC, jrandiny commented on utils/context/constants/company-profile/about-us-data.ts
> +const items = [
kenapa ini di utils/**context**/ ya

2020-12-03 09:43 UTC, jrandiny commented on utils/context/constants/company-profile/gallery-text.ts
> +const galleryItems = [
Ini juga kenapa

2020-12-19 00:53 UTC, 16519111 commented on components/commons/company-profile/Gallery/gallery-alt.tsx
> +                  {pages.map(() => {
```<Carousel 
              itemsToShow={3}
              renderPagination={({ pages }) => {
                pages.map(() => {
                  return (
                    null
                  );
                });}
              }>
```
Tadi udah dicoba gini tapi dari renderPaginationnya error kak

2020-12-19 00:57 UTC, 16519111 commented on package.json
> +    "styled-components": "^5.2.1",
itu di dokumentasi react elastic carousel katanya suruh pake itu kak buat styling. Udh kutanyain juga ke niel katanya dia install juga jadi aku install

2020-12-30 15:00 UTC, jrandiny commented
Main
- Tombol carousel gak centered
- Tombol gak punya highlight pake widget yang dari main site aja
- Background belum ada
- Video player gada yang tombol chat sama icon gambar video di pojok kanan bawah

2020-12-30 15:08 UTC, jrandiny commented
Alt
- tombol carousel beda dan tidak centered
- Background belum ada

2021-01-16 16:36 UTC, merged